// List  templates
export const shapes = {
  slab: {
    type: 'slab',
    name: 'Slab',
    subtotals: 0,
    totals: [],
    template: [
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { quantity: 1 },
    ],
  },
  wall: {
    type: 'wall',
    name: 'Wall',
    subtotals: 0,
    totals: [],
    template: [
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { quantity: 1 },
    ],
  },
  triangle: {
    type: 'triangle',
    name: 'Triangle',
    subtotals: 0,
    totals: [],
    template: [
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { quantity: 1 },
    ],
  },
  column: {
    type: 'column',
    name: 'Column',
    subtotals: 0,
    totals: [],
    template: [{ unit1: null, unit2: null }, { unit1: null, unit2: null }, { quantity: 1 }],
  },
  curbGutter: {
    type: 'curbGutter',
    name: 'Curb / Gutter',
    subtotals: 0,
    totals: [],
    template: [
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { quantity: 1 },
    ],
  },
  stairs: {
    type: 'stairs',
    name: 'Stairs',
    subtotals: 0,
    totals: [],
    template: [
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { stepCount: null },
      { quantity: 1 },
    ],
  },
  tube: {
    type: 'tube',
    name: 'Circle / Tube',
    subtotals: 0,
    totals: [],
    template: [
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { quantity: 1 },
    ],
  },
  rebar: {
    type: 'rebar',
    name: 'Rebar',
    subtotals: 0,
    totals: [],
    template: [
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { unit1: null, unit2: null },
      { quantity: 1 },
    ],
  },
};
